"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, Heart, Plus, Sparkles } from "lucide-react";
import { toast } from "sonner";

const suggestedBills = ["Rent or mortgage", "Electricity", "Water", "Internet", "Cell phones", "Car payment", "Car insurance", "Groceries"];

export default function OnboardingPage() {
  const [step,setStep]=useState(1);
  const [selected,setSelected]=useState(["Rent or mortgage","Electricity","Internet","Groceries"]);
  const router=useRouter();
  function finish(){toast.success("Your household is ready", {description:"Welcome to Couples Budget."});router.push("/dashboard?demo=true")}
  return <div className="min-h-screen bg-[#f6f8f7] px-4 py-7 sm:px-6"><div className="mx-auto max-w-3xl">
    <div className="flex items-center justify-between"><div className="flex items-center gap-2 font-bold"><span className="grid size-9 place-items-center rounded-xl bg-navy text-emerald-400"><Heart className="size-5 fill-current"/></span>Couples Budget</div><button onClick={finish} className="text-xs font-bold text-slate-500">Skip for now</button></div>
    <div className="mt-10 flex items-center gap-2">{[1,2,3].map(i=><div key={i} className="flex flex-1 items-center gap-2"><span className={`grid size-7 shrink-0 place-items-center rounded-full text-xs font-bold ${i<=step?"bg-brand text-white":"bg-slate-200 text-slate-500"}`}>{i<step?<Check className="size-3.5"/>:i}</span><div className={`h-1 flex-1 rounded-full ${i<=step?"bg-brand":"bg-slate-200"} ${i===3?"hidden":""}`}/></div>)}</div>
    <div className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5 sm:p-10">
      {step===1&&<div><span className="grid size-12 place-items-center rounded-2xl bg-emerald-50 text-brand"><Heart/></span><h1 className="mt-5 text-3xl font-bold">Set up your household</h1><p className="mt-2 text-slate-500">A few basics so your shared budget feels like yours.</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><Field label="Your name" value="Abel"/><Field label="Partner's name" value="Maya"/><Field label="Household name" value="Abel & Maya Household"/><label className="text-xs font-bold">Budget month<select className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-3 font-normal"><option>August 2026</option></select></label><label className="text-xs font-bold">Preferred currency<select className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-3 font-normal"><option>USD — US Dollar</option><option>CAD — Canadian Dollar</option><option>GBP — British Pound</option><option>EUR — Euro</option></select></label><Field label="Monthly savings goal" value="1000" type="number"/></div></div>}
      {step===2&&<div><span className="grid size-12 place-items-center rounded-2xl bg-blue-50 text-blue-600"><Sparkles/></span><h1 className="mt-5 text-3xl font-bold">Add monthly income</h1><p className="mt-2 text-slate-500">Start with one source. You can add more anytime.</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><Field label="Income source" value="Primary paycheck"/><label className="text-xs font-bold">Received by<select className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-3 font-normal"><option>Abel</option><option>Maya</option><option>Joint household</option></select></label><Field label="Expected monthly amount" value="4200" type="number"/><label className="text-xs font-bold">Pay frequency<select className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-3 font-normal"><option>Twice monthly</option><option>Biweekly</option><option>Monthly</option><option>Irregular</option></select></label><Field label="Expected pay date" value="2026-08-01" type="date"/><label className="flex items-center gap-3 self-end rounded-xl bg-slate-50 p-4 text-xs font-bold"><input type="checkbox" defaultChecked className="size-4 accent-emerald-600"/>This income repeats</label></div><button onClick={()=>toast.success("Another income row added")} className="mt-5 flex items-center gap-2 text-xs font-bold text-emerald-700"><Plus className="size-4"/>Add another income source</button></div>}
      {step===3&&<div><span className="grid size-12 place-items-center rounded-2xl bg-amber-50 text-amber-600"><Check/></span><h1 className="mt-5 text-3xl font-bold">Choose your common bills</h1><p className="mt-2 text-slate-500">We&apos;ll create editable starter items for this month.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{suggestedBills.map(b=><button onClick={()=>setSelected(selected.includes(b)?selected.filter(i=>i!==b):[...selected,b])} key={b} className={`flex items-center justify-between rounded-xl border p-4 text-left text-sm font-semibold ${selected.includes(b)?"border-emerald-400 bg-emerald-50":"border-slate-200"}`}>{b}<span className={`grid size-5 place-items-center rounded-full ${selected.includes(b)?"bg-brand text-white":"border border-slate-300"}`}>{selected.includes(b)&&<Check className="size-3"/>}</span></button>)}</div><p className="mt-4 text-xs text-slate-400">No sensitive account numbers are ever required.</p></div>}
      <div className="mt-10 flex justify-between border-t border-slate-100 pt-6"><button disabled={step===1} onClick={()=>setStep(step-1)} className="flex h-11 items-center gap-2 rounded-xl px-4 text-sm font-bold text-slate-600 disabled:opacity-0"><ArrowLeft className="size-4"/>Back</button><button onClick={()=>step===3?finish():setStep(step+1)} className="flex h-11 items-center gap-2 rounded-xl bg-navy px-6 text-sm font-bold text-white">{step===3?"Finish setup":"Continue"}<ArrowRight className="size-4"/></button></div>
    </div>
  </div></div>
}
function Field({label,value,type="text"}:{label:string;value:string;type?:string}){return <label className="text-xs font-bold">{label}<input defaultValue={value} type={type} className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-3 font-normal outline-none focus:border-emerald-400"/></label>}
