"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { CalendarDays, Check, CircleDollarSign, Download, FileText, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import {
  createBillAction, createIncomeAction, createSavingsContributionAction, createSavingsGoalAction,
  createTransactionAction, deleteFinancialRecordAction, markBillPaidAction, updateSettingsAction,
  type ActionResult,
} from "@/app/actions/financial";
import type { FinancialData } from "@/lib/data/financial";
import { cn, formatCurrency } from "@/lib/utils";

type PageProps = { data: FinancialData };
type FormKind = "bill" | "income" | "transaction" | "goal" | "contribution";

function Heading({ title, description, action, onAction, disabled = false }: { title: string; description: string; action?: string; onAction?: () => void; disabled?: boolean }) {
  return <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div>{action&&<button disabled={disabled} onClick={onAction} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-navy px-4 text-xs font-bold text-white disabled:opacity-50"><Plus className="size-4"/>{action}</button>}</div>;
}
function Summary({ items }: { items: [string, string, string?][] }) {
  return <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map(([label,value,color])=><div key={label} className="surface rounded-2xl p-5"><p className="text-xs font-medium text-slate-500">{label}</p><p className={cn("mt-2 text-2xl font-bold",color)}>{value}</p></div>)}</div>;
}
function Card({ children, className }: { children: React.ReactNode; className?: string }) { return <section className={cn("surface rounded-2xl p-5 sm:p-6",className)}>{children}</section>; }
function Empty({ title, body }: { title: string; body: string }) { return <div className="grid min-h-48 place-items-center rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-8 text-center"><div><p className="font-bold">{title}</p><p className="mt-1 text-sm text-slate-500">{body}</p></div></div>; }
const day = (date: string) => new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(`${date.slice(0,10)}T00:00:00Z`));

function useMutation() {
  const [pending,startTransition]=useTransition();
  const router=useRouter();
  const run=(work:()=>Promise<ActionResult>,done?:()=>void)=>startTransition(async()=>{const result=await work();if(result.ok)toast.success(result.message);else toast.error(result.message);if(result.ok){done?.();router.refresh();}});
  const remove=(entity:"bill"|"income"|"transaction"|"goal"|"contribution",id:string)=>{if(confirm("Delete this record permanently?"))run(()=>deleteFinancialRecordAction(entity,id));};
  return {pending,run,remove};
}

export function BillsFeaturePage({data}:PageProps) {
  const [form,setForm]=useState(false); const {pending,run,remove}=useMutation();
  const paid=data.bills.filter(b=>b.status==="paid"); const upcoming=data.bills.filter(b=>b.status==="planned");
  return <div><Heading title="Bills" description="Every payment and due date in one place." action="Add bill" onAction={()=>setForm(true)}/>
    <Summary items={[["Monthly total",formatCurrency(data.bills.reduce((s,b)=>s+b.amount,0))],["Paid",formatCurrency(paid.reduce((s,b)=>s+b.amount,0)),"text-emerald-600"],["Upcoming",`${upcoming.length} bill${upcoming.length===1?"":"s"}`,"text-amber-600"],["Recurring",`${data.bills.filter(b=>b.recurring).length} active`]]}/>
    <Card className="mt-4">{!data.bills.length?<Empty title="No bills yet" body="Add your first monthly bill to track its due date and payment status."/>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.bills.map(b=><article key={b.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between"><span className="grid size-11 place-items-center rounded-xl bg-slate-100 font-bold">{b.name[0]}</span><button onClick={()=>remove("bill",b.id)} aria-label={`Delete ${b.name}`}><Trash2 className="size-4 text-slate-400 hover:text-red-500"/></button></div><h2 className="mt-4 font-bold">{b.name}</h2><p className="mt-1 text-xs text-slate-500">{b.category} · Due {day(b.dueDate)}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><b>{formatCurrency(b.amount)}</b><button disabled={pending||b.status!=="planned"} onClick={()=>run(()=>markBillPaidAction(b.id))} className={cn("rounded-full px-2.5 py-1 text-[10px] font-bold capitalize",b.status==="paid"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700")}>{b.status==="planned"?"Mark paid":b.status}</button></div></article>)}</div>}</Card>
    {form&&<RecordForm kind="bill" data={data} pending={pending} close={()=>setForm(false)} submit={fd=>run(()=>createBillAction(fd),()=>setForm(false))}/>}</div>;
}

export function IncomeFeaturePage({data}:PageProps) {
  const [form,setForm]=useState(false); const {pending,run,remove}=useMutation(); const total=data.income.reduce((s,i)=>s+i.amount,0);
  return <div><Heading title="Income" description="Track income received by your household." action="Add income" onAction={()=>setForm(true)}/><Summary items={[["Household income",formatCurrency(total)],["Entries",String(data.income.length)],["Recurring",String(data.income.filter(i=>i.recurring).length)],["Latest",data.income[0]?day(data.income[0].receivedOn):"None yet"]]}/>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><Card><h2 className="font-bold">Monthly income</h2>{!data.reports.length?<Empty title="No trend yet" body="Monthly income will appear after you record it."/>:<div className="mt-4 h-64"><ResponsiveContainer><BarChart data={data.reports}><CartesianGrid stroke="#eef0f2" vertical={false}/><XAxis dataKey="month" tickFormatter={v=>day(String(v))} axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={v=>formatCurrency(Number(v))}/><Bar dataKey="income" fill="#00a866" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div>}</Card>
    <Card><h2 className="font-bold">Income entries</h2>{!data.income.length?<Empty title="No income recorded" body="Add paychecks or other household income."/>:<div className="mt-3 divide-y divide-slate-100">{data.income.map(i=><div key={i.id} className="flex items-center gap-3 py-4"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><CircleDollarSign className="size-5"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{i.description}</p><p className="text-xs text-slate-500">{i.receivedBy??"Household"} · {day(i.receivedOn)}</p></div><b className="text-sm">{formatCurrency(i.amount)}</b><button onClick={()=>remove("income",i.id)}><Trash2 className="size-4 text-slate-400"/></button></div>)}</div>}</Card></div>
    {form&&<RecordForm kind="income" data={data} pending={pending} close={()=>setForm(false)} submit={fd=>run(()=>createIncomeAction(fd),()=>setForm(false))}/>}</div>;
}

export function SpendingFeaturePage({data}:PageProps) {
  const [form,setForm]=useState(false); const {pending,run,remove}=useMutation(); const spent=data.transactions.reduce((s,t)=>s+(t.kind==="expense"?t.amount:t.kind==="refund"?-t.amount:0),0); const budget=data.budgets.reduce((s,b)=>s+b.amount,0);
  return <div><Heading title="Spending" description="Stay on top of everyday household purchases." action="Add transaction" onAction={()=>setForm(true)}/><Summary items={[["Spent this month",formatCurrency(spent)],["Flexible budget",formatCurrency(budget)],["Remaining",formatCurrency(budget-spent),budget-spent>=0?"text-emerald-600":"text-red-600"],["Transactions",String(data.transactions.length)]]}/>
    <div className="mt-4 grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><Card><h2 className="font-bold">Category budgets</h2>{!data.budgets.length?<Empty title="No category budgets" body="Category budgets will appear after they are configured."/>:<div className="mt-6 space-y-6">{data.budgets.map(b=>{const pct=b.amount?Math.round(b.spent/b.amount*100):0;return <div key={b.id}><div className="flex justify-between text-xs"><b>{b.category}</b><span>{formatCurrency(b.spent)} of {formatCurrency(b.amount)}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className={cn("h-full rounded-full",pct>=100?"bg-red-500":pct>=75?"bg-amber-500":"bg-emerald-500")} style={{width:`${Math.min(pct,100)}%`}}/></div></div>})}</div>}</Card>
    <Card><h2 className="font-bold">Recent transactions</h2>{!data.transactions.length?<Empty title="No transactions yet" body="Add a purchase, refund, or transfer to start tracking spending."/>:<div className="mt-3 divide-y divide-slate-100">{data.transactions.map(t=><div key={t.id} className="flex items-center gap-3 py-4"><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{t.description}</p><p className="text-xs text-slate-500">{day(t.date)} · {t.category??t.kind} · {t.paidBy??"Household"}</p></div><b className={cn("text-sm",t.kind==="refund"&&"text-emerald-600")}>{t.kind==="refund"?"+":"−"}{formatCurrency(t.amount)}</b><button onClick={()=>remove("transaction",t.id)}><Trash2 className="size-4 text-slate-400"/></button></div>)}</div>}</Card></div>
    {form&&<RecordForm kind="transaction" data={data} pending={pending} close={()=>setForm(false)} submit={fd=>run(()=>createTransactionAction(fd),()=>setForm(false))}/>}</div>;
}

export function SavingsFeaturePage({data}:PageProps) {
  const [form,setForm]=useState<FormKind|null>(null); const [goalId,setGoalId]=useState(""); const {pending,run,remove}=useMutation(); const saved=data.goals.reduce((s,g)=>s+g.saved,0);
  return <div><Heading title="Savings goals" description="Turn shared plans into visible progress." action="Create goal" onAction={()=>setForm("goal")}/><Summary items={[["Total saved",formatCurrency(saved),"text-emerald-600"],["Combined targets",formatCurrency(data.goals.reduce((s,g)=>s+g.targetAmount,0))],["Contributions",String(data.contributions.length)],["Active goals",String(data.goals.filter(g=>!g.completed).length)]]}/>
    {!data.goals.length?<div className="mt-4"><Empty title="No savings goals yet" body="Create a goal, then record contributions as you save."/></div>:<div className="mt-4 grid gap-4 lg:grid-cols-3">{data.goals.map(g=>{const pct=Math.min(100,Math.round(g.saved/g.targetAmount*100));return <Card key={g.id}><div className="flex justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-emerald-50 text-emerald-600"><Check/></span><button onClick={()=>remove("goal",g.id)}><Trash2 className="size-4 text-slate-400"/></button></div><h2 className="mt-5 text-lg font-bold">{g.name}</h2><p className="mt-1 text-xs text-slate-500">{g.targetDate?`Target ${day(g.targetDate)}`:"No target date"}</p><div className="mt-6 flex justify-between"><b className="text-2xl">{formatCurrency(g.saved)}</b><b className="text-emerald-600">{pct}%</b></div><div className="mt-3 h-2.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand" style={{width:`${pct}%`}}/></div><p className="mt-3 text-xs text-slate-500">{formatCurrency(Math.max(0,g.targetAmount-g.saved))} remaining</p><button onClick={()=>{setGoalId(g.id);setForm("contribution")}} className="mt-5 w-full rounded-xl bg-navy py-2.5 text-xs font-bold text-white">Add contribution</button></Card>})}</div>}
    {!!data.contributions.length&&<Card className="mt-4"><h2 className="font-bold">Recent contributions</h2><div className="mt-3 divide-y divide-slate-100">{data.contributions.slice(0,8).map(c=><div key={c.id} className="flex items-center gap-3 py-3 text-sm"><div className="min-w-0 flex-1"><b>{c.goalName}</b><p className="text-xs text-slate-500">{day(c.date)}{c.note?` · ${c.note}`:""}</p></div><b className="text-emerald-600">+{formatCurrency(c.amount)}</b><button onClick={()=>remove("contribution",c.id)} aria-label={`Delete contribution to ${c.goalName}`}><Trash2 className="size-4 text-slate-400"/></button></div>)}</div></Card>}
    {form&&<RecordForm kind={form} data={data} goalId={goalId} pending={pending} close={()=>setForm(null)} submit={fd=>run(()=>form==="goal"?createSavingsGoalAction(fd):createSavingsContributionAction(fd),()=>setForm(null))}/>}</div>;
}

export function CalendarFeaturePage({data}:PageProps) {
  const month=data.month?.monthStart??new Date().toISOString().slice(0,7)+"-01"; const date=new Date(`${month.slice(0,10)}T00:00:00Z`); const days=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth()+1,0)).getUTCDate(); const offset=date.getUTCDay();
  const events=new Map<number,{label:string;amount:number;color:string}[]>(); const add=(raw:string,event:{label:string;amount:number;color:string})=>{const d=Number(raw.slice(8,10));events.set(d,[...(events.get(d)??[]),event]);};
  data.bills.forEach(b=>add(b.dueDate,{label:b.name,amount:b.amount,color:b.status==="paid"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"})); data.income.forEach(i=>add(i.receivedOn,{label:i.description,amount:i.amount,color:"bg-blue-100 text-blue-700"})); data.contributions.filter(c=>c.date.startsWith(month.slice(0,7))).forEach(c=>add(c.date,{label:c.goalName,amount:c.amount,color:"bg-violet-100 text-violet-700"}));
  return <div><Heading title="Budget calendar" description="Income, bills, and savings on one real timeline."/><Card className="mt-6"><div className="flex items-center justify-center gap-2"><CalendarDays className="size-5 text-emerald-600"/><h2 className="text-lg font-bold">{new Intl.DateTimeFormat("en-US",{month:"long",year:"numeric",timeZone:"UTC"}).format(date)}</h2></div><div className="mt-5 grid grid-cols-7 overflow-hidden rounded-xl border border-slate-200">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><div key={d} className="border-b bg-slate-50 p-2 text-center text-[10px] font-bold text-slate-500">{d}</div>)}{Array.from({length:Math.ceil((offset+days)/7)*7},(_,i)=>{const d=i-offset+1;return <div key={i} className="min-h-28 border-b border-r border-slate-100 p-1.5"><span className="text-[10px] text-slate-500">{d>0&&d<=days?d:""}</span>{events.get(d)?.map((e,j)=><div key={`${e.label}-${j}`} className={cn("mt-1 truncate rounded px-1.5 py-1 text-[9px] font-bold",e.color)}>{e.label} {formatCurrency(e.amount)}</div>)}</div>})}</div>{!events.size&&<p className="mt-4 text-center text-sm text-slate-500">No dated financial activity this month.</p>}</Card></div>;
}

export function ReportsFeaturePage({data}:PageProps) {
  const current=data.reports.at(-1)??{income:0,expenses:0,saved:0,month:""}; const remaining=current.income-current.expenses-current.saved;
  const exportCsv=()=>{if(!data.reports.length)return toast.error("There is no report data to export yet.");const csv=["Month,Income,Expenses,Saved",...data.reports.map(r=>`${r.month},${r.income},${r.expenses},${r.saved}`)].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="household-report.csv";a.click();URL.revokeObjectURL(url);toast.success("CSV report downloaded.");};
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold sm:text-3xl">Reports</h1><p className="mt-1 text-sm text-slate-500">Understand your household&apos;s real financial progress.</p></div><div className="flex gap-2"><button onClick={()=>window.print()} className="flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-xs font-bold"><FileText className="size-4"/>Print / PDF</button><button onClick={exportCsv} className="flex h-10 items-center gap-2 rounded-xl bg-navy px-4 text-xs font-bold text-white"><Download className="size-4"/>Export CSV</button></div></div><Summary items={[["Total income",formatCurrency(current.income)],["Total expenses",formatCurrency(current.expenses)],["Money remaining",formatCurrency(remaining),remaining>=0?"text-emerald-600":"text-red-600"],["Savings rate",current.income?`${(current.saved/current.income*100).toFixed(1)}%`:"0%","text-emerald-600"]]}/><Card className="mt-4"><h2 className="font-bold">Income vs. expenses</h2>{!data.reports.length?<Empty title="No report data yet" body="Reports populate as you record monthly financial activity."/>:<div className="mt-4 h-72"><ResponsiveContainer><BarChart data={data.reports}><CartesianGrid stroke="#eef0f2" vertical={false}/><XAxis dataKey="month" tickFormatter={v=>day(String(v))}/><YAxis tickFormatter={v=>`$${v/1000}k`}/><Tooltip formatter={v=>formatCurrency(Number(v))}/><Bar dataKey="income" fill="#00a866"/><Bar dataKey="expenses" fill="#111827"/></BarChart></ResponsiveContainer></div>}</Card></div>;
}

export function SettingsFeaturePage({data}:PageProps) {
  const {pending,run}=useMutation();
  const [inviteUrl,setInviteUrl]=useState("");
  if(!data.household)return <Empty title="No household found" body="Complete household setup before changing settings."/>;
  return <div><Heading title="Household settings" description="Shared details and your personal preferences."/>
    <div className="mt-6 grid gap-4 xl:grid-cols-2">
      <Card><form onSubmit={e=>{e.preventDefault();run(()=>updateSettingsAction(new FormData(e.currentTarget)))}}><div className="grid gap-5 sm:grid-cols-2"><Field label="Household name" name="householdName" defaultValue={data.household.name}/><Field label="Locale" name="locale" defaultValue={data.preferences?.locale??"en-US"}/><label className="text-xs font-bold">Currency<input readOnly value={data.household.currencyCode} className="mt-2 h-11 w-full rounded-xl border bg-slate-50 px-3 font-normal"/></label><label className="text-xs font-bold">Theme<select name="theme" defaultValue={data.preferences?.theme??"system"} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label></div><div className="mt-6 flex flex-wrap gap-6"><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="emailNotifications" defaultChecked={data.preferences?.emailNotifications}/>Email notifications</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="pushNotifications" defaultChecked={data.preferences?.pushNotifications}/>Push notifications</label></div><div className="mt-7 border-t pt-5"><p className="text-xs font-bold text-slate-500">Active members</p><p className="mt-2 text-sm">{data.members.map(m=>m.name).join(" · ")||"No active members"}</p></div><button disabled={pending} className="mt-7 rounded-xl bg-brand px-5 py-3 text-xs font-bold text-white disabled:opacity-60">{pending?"Saving…":"Save changes"}</button></form></Card>
      <Card>
        <h2 className="font-bold">Invite your partner</h2>
        <p className="mt-1 text-xs text-slate-500">Each household supports two partners with separate logins.</p>
        <form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);run(async()=>{const {invitePartnerAction}=await import("@/app/actions/invitations");const result=await invitePartnerAction(fd);if(result.ok&&result.token){const url=`${window.location.origin}/invite/${result.token}`;setInviteUrl(url);await navigator.clipboard.writeText(url).catch(()=>undefined);}return result;});}}>
          <Field label="Partner email" name="email" type="email"/>
          <button disabled={pending||data.members.length>=2} className="rounded-xl bg-navy px-5 py-3 text-xs font-bold text-white disabled:opacity-50">{data.members.length>=2?"Household is full":pending?"Creating…":"Create invite link"}</button>
        </form>
        {inviteUrl&&<p className="mt-4 break-all rounded-xl bg-emerald-50 p-3 text-xs text-emerald-800">Invite link copied:<br/>{inviteUrl}</p>}
      </Card>
    </div>
  </div>;
}

function RecordForm({kind,data,goalId,pending,close,submit}:{kind:FormKind;data:FinancialData;goalId?:string;pending:boolean;close:()=>void;submit:(form:FormData)=>void}) {
  const today=new Date().toISOString().slice(0,10); const titles={bill:"Add bill",income:"Add income",transaction:"Add transaction",goal:"Create savings goal",contribution:"Add contribution"};
  return <div className="fixed inset-0 z-[70] grid place-items-end bg-slate-950/40 backdrop-blur-sm sm:place-items-center sm:p-5" onMouseDown={close}><form onSubmit={e=>{e.preventDefault();submit(new FormData(e.currentTarget))}} onMouseDown={e=>e.stopPropagation()} className="w-full max-w-lg rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl"><div className="flex justify-between"><h2 className="text-xl font-bold">{titles[kind]}</h2><button type="button" onClick={close}>×</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">
    {kind==="bill"&&<><Field label="Bill name" name="name"/><Field label="Amount" name="amount" type="number"/>{data.categories.some(c=>c.kind==="expense")?<Select label="Category" name="categoryId" options={data.categories.filter(c=>c.kind==="expense").map(c=>[c.id,c.name])}/>:<Field label="Category" name="categoryName" defaultValue="Bills"/>}<Field label="Due date" name="dueDate" type="date" defaultValue={today}/><CheckField label="Recurring" name="recurring"/></>}
    {kind==="income"&&<><Field label="Description" name="description"/><Field label="Amount" name="amount" type="number"/><Field label="Received on" name="receivedOn" type="date" defaultValue={today}/><Select label="Category (optional)" name="categoryId" optional options={data.categories.filter(c=>c.kind==="income").map(c=>[c.id,c.name])}/><CheckField label="Recurring" name="recurring"/></>}
    {kind==="transaction"&&<><Field label="Description" name="description"/><Field label="Amount" name="amount" type="number"/><Field label="Date" name="transactionDate" type="date" defaultValue={today}/><Select label="Category (optional)" name="categoryId" optional options={data.categories.filter(c=>c.kind==="expense").map(c=>[c.id,c.name])}/><Select label="Type" name="kind" options={[["expense","Expense"],["refund","Refund"],["transfer","Transfer"]]}/></>}
    {kind==="goal"&&<><Field label="Goal name" name="name"/><Field label="Target amount" name="targetAmount" type="number"/><Field label="Target date (optional)" name="targetDate" type="date" required={false}/></>}
    {kind==="contribution"&&<><input type="hidden" name="goalId" value={goalId}/><Field label="Amount" name="amount" type="number"/><Field label="Date" name="contributedOn" type="date" defaultValue={today}/><Field label="Note (optional)" name="note" required={false}/></>}
  </div><button disabled={pending} className="mt-6 h-11 w-full rounded-xl bg-brand font-bold text-white disabled:opacity-60">{pending?"Saving…":titles[kind]}</button></form></div>;
}
function Field({label,name,type="text",defaultValue,required=true}:{label:string;name:string;type?:string;defaultValue?:string;required?:boolean}) { return <label className="text-xs font-bold">{label}<input required={required} name={name} type={type} defaultValue={defaultValue} min={type==="number"?"0.01":undefined} step={type==="number"?"0.01":undefined} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal outline-none focus:border-emerald-400"/></label>; }

function Select({label,name,options,optional=false}:{label:string;name:string;options:[string,string][];optional?:boolean}) { return <label className="text-xs font-bold">{label}<select required={!optional} name={name} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal">{optional&&<option value="">None</option>}{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>; }
function CheckField({label,name}:{label:string;name:string}) { return <label className="flex items-center gap-2 self-end pb-3 text-xs font-bold"><input type="checkbox" name={name}/>{label}</label>; }
