"use client";

import { useState } from "react";
import {
  Bell, Car, Check, ChevronLeft, ChevronRight, CircleDollarSign,
  Download, FileText, Filter, Fuel, Home, Mail, MoreHorizontal, Plane,
  Plus, Search, Settings2, Shield, ShoppingBasket, Trash2, Utensils,
} from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { bills, categoryBudgets, income, savingsGoals, transactions } from "@/lib/demo-data";
import { cn, formatCurrency } from "@/lib/utils";

function Heading({title,description,action="Add new",onAction}:{title:string;description:string;action?:string;onAction?:()=>void}) {
  return <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div><button onClick={onAction??(()=>toast.success(`${action} is ready`))} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-navy px-4 text-xs font-bold text-white"><Plus className="size-4"/>{action}</button></div>;
}
function Summary({items}:{items:[string,string,string?][]}) {
  return <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map(([label,value,color])=><div key={label} className="surface rounded-2xl p-5"><p className="text-xs font-medium text-slate-500">{label}</p><p className={cn("mt-2 text-2xl font-bold",color)}>{value}</p></div>)}</div>;
}
function Card({children,className}:{children:React.ReactNode;className?:string}) { return <section className={cn("surface rounded-2xl p-5 sm:p-6",className)}>{children}</section>; }

export function BillsFeaturePage() {
  const [view,setView]=useState<"list"|"calendar">("list");
  return <div><Heading title="Bills" description="Every recurring payment, due date, and responsibility in one place." action="Add bill"/><Summary items={[["Monthly total","$3,640"],["Paid this month","$2,189","text-emerald-600"],["Upcoming","5 bills","text-amber-600"],["Autopay","2 active","text-blue-600"]]}/><Card className="mt-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex rounded-lg bg-slate-100 p-1 text-xs font-bold"><button onClick={()=>setView("list")} className={cn("rounded-md px-4 py-2",view==="list"&&"bg-white shadow-sm")}>List</button><button onClick={()=>setView("calendar")} className={cn("rounded-md px-4 py-2",view==="calendar"&&"bg-white shadow-sm")}>Calendar</button></div><div className="flex gap-2"><button className="rounded-lg border border-slate-200 p-2"><Search className="size-4"/></button><button className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 text-xs font-bold"><Filter className="size-4"/>Filters</button></div></div>{view==="list"?<div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{bills.map(b=><div key={b.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-slate-100 font-bold">{b.name[0]}</span><MoreHorizontal className="size-4 text-slate-400"/></div><div className="mt-4 flex items-end justify-between"><div><h3 className="font-bold">{b.name}</h3><p className="mt-1 text-xs text-slate-500">{b.category} · Due {b.due}</p></div><p className="text-lg font-bold">{formatCurrency(b.actual)}</p></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-xs text-slate-500">Assigned to <b className="text-slate-800">{b.assigned}</b></span><span className={cn("rounded-full px-2 py-1 text-[10px] font-bold",b.status==="Paid"?"bg-emerald-100 text-emerald-700":b.status==="Late"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700")}>{b.status}</span></div></div>)}</div>:<MiniCalendar/>}</Card></div>;
}

export function IncomeFeaturePage() {
  const chart=[{m:"Mar",income:7740},{m:"Apr",income:8050},{m:"May",income:7920},{m:"Jun",income:8350},{m:"Jul",income:8180},{m:"Aug",income:8520}];
  return <div><Heading title="Income" description="Track expected and received income for both partners." action="Add income"/><Summary items={[["Expected household","$8,450"],["Actual household","$8,520","text-emerald-600"],["Abel","$4,200"],["Maya","$4,320"]]}/><div className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Card><h2 className="font-bold">Monthly income</h2><p className="mt-1 text-xs text-slate-500">Last six months</p><div className="mt-4 h-64"><ResponsiveContainer><LineChart data={chart}><CartesianGrid stroke="#eef0f2" vertical={false}/><XAxis dataKey="m" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={(v)=>formatCurrency(Number(v))}/><Line type="monotone" dataKey="income" stroke="#00a866" strokeWidth={3} dot={{fill:"#00a866",r:4}}/></LineChart></ResponsiveContainer></div></Card><Card><h2 className="font-bold">Income sources</h2><div className="mt-4 divide-y divide-slate-100">{income.map(i=><div key={i.id} className="flex items-center gap-3 py-4"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><CircleDollarSign className="size-5"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{i.source}</p><p className="text-xs text-slate-500">{i.partner} · {i.frequency}</p></div><div className="text-right"><b className="text-sm">{formatCurrency(i.actual)}</b><p className="text-[10px] text-emerald-600">{i.date}</p></div></div>)}</div></Card></div></div>;
}

export function SpendingFeaturePage() {
  return <div><Heading title="Spending" description="Stay on top of everyday purchases without overthinking it." action="Add transaction"/><Summary items={[["Spent this month","$1,682"],["Flexible budget","$2,250"],["Remaining","$568","text-emerald-600"],["Largest category","Groceries"]]}/><div className="mt-4 grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><Card><h2 className="font-bold">Category budgets</h2><p className="mt-1 text-xs text-slate-500">We&apos;ll warn you at 75%, 90%, and 100%.</p><div className="mt-6 space-y-6">{categoryBudgets.map(c=>{const pct=Math.round(c.spent/c.budget*100);return <div key={c.name}><div className="flex items-center justify-between text-xs"><span className="font-bold">{c.name}</span><span><b>{formatCurrency(c.spent)}</b> <span className="text-slate-400">of {formatCurrency(c.budget)}</span></span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className={cn("h-full rounded-full",pct>=90?"bg-red-500":pct>=75?"bg-amber-500":"bg-emerald-500")} style={{width:`${Math.min(pct,100)}%`}}/></div><p className={cn("mt-1 text-right text-[10px]",pct>=90?"text-red-600":pct>=75?"text-amber-600":"text-slate-400")}>{pct}% used</p></div>})}</div></Card><Card><div className="flex items-center justify-between"><div><h2 className="font-bold">Recent transactions</h2><p className="mt-1 text-xs text-slate-500">Shared household activity</p></div><button className="rounded-lg border border-slate-200 p-2"><Search className="size-4"/></button></div><div className="mt-4 divide-y divide-slate-100">{transactions.map(t=><div key={t.id} className="flex items-center gap-3 py-4"><span className="grid size-10 place-items-center rounded-xl bg-slate-100 text-slate-600">{t.category==="Groceries"?<ShoppingBasket className="size-5"/>:t.category==="Gas"?<Fuel className="size-5"/>:t.category==="Dining out"?<Utensils className="size-5"/>:<Home className="size-5"/>}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{t.name}</p><p className="text-xs text-slate-500">{t.date} · {t.category} · {t.paidBy}</p></div><b className="text-sm">−{formatCurrency(t.amount)}</b></div>)}</div></Card></div></div>;
}

export function SavingsFeaturePage() {
  return <div><Heading title="Savings goals" description="Turn the future you talk about into progress you can see." action="Create goal"/><Summary items={[["Total saved","$15,650","text-emerald-600"],["Combined targets","$31,500"],["This month","$1,400"],["Active goals","3"]]}/><div className="mt-4 grid gap-4 lg:grid-cols-3">{savingsGoals.map((g,i)=>{const pct=Math.round(g.saved/g.target*100);const Icon=i===0?Shield:i===1?Plane:Car;return <Card key={g.id}><div className="flex items-start justify-between"><span className={cn("grid size-12 place-items-center rounded-2xl",i===0?"bg-emerald-50 text-emerald-600":i===1?"bg-violet-50 text-violet-600":"bg-amber-50 text-amber-600")}><Icon/></span><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{g.priority} priority</span></div><h2 className="mt-5 text-lg font-bold">{g.name}</h2><p className="mt-1 text-xs text-slate-500">Target: {g.targetDate}</p><div className="mt-6 flex items-end justify-between"><p className="text-2xl font-bold">{formatCurrency(g.saved)}</p><b className="text-sm text-emerald-600">{pct}%</b></div><div className="mt-3 h-2.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand" style={{width:`${pct}%`}}/></div><div className="mt-4 flex justify-between text-xs text-slate-500"><span>{formatCurrency(g.target-g.saved)} remaining</span><span>{formatCurrency(g.monthly)}/mo</span></div><button onClick={()=>toast.success(`Contribution recorded for ${g.name}`)} className="mt-5 w-full rounded-xl bg-navy py-2.5 text-xs font-bold text-white">Add contribution</button></Card>})}</div></div>;
}

export function CalendarFeaturePage() {
  return <div><Heading title="Budget calendar" description="Income, bills, savings, and reminders on one timeline." action="Add item"/><Card className="mt-6"><div className="flex items-center justify-between"><button className="grid size-9 place-items-center rounded-lg border border-slate-200"><ChevronLeft className="size-4"/></button><h2 className="text-lg font-bold">August 2026</h2><button className="grid size-9 place-items-center rounded-lg border border-slate-200"><ChevronRight className="size-4"/></button></div><div className="mt-5 flex flex-wrap justify-center gap-4 text-[10px]">{[["bg-blue-500","Income"],["bg-amber-500","Bill due"],["bg-emerald-500","Paid"],["bg-violet-500","Savings"],["bg-red-500","Overdue"]].map(([c,l])=><span key={l} className="flex items-center gap-1.5"><i className={cn("size-2 rounded-full",c)}/>{l}</span>)}</div><MiniCalendar full/></Card></div>;
}

function MiniCalendar({full=false}:{full?:boolean}) {
  const events:Record<number,[string,string,string][]>={1:[["Payday","$4,200","bg-blue-100 text-blue-700"],["Rent paid","$1,950","bg-emerald-100 text-emerald-700"]],4:[["Electricity","$168","bg-emerald-100 text-emerald-700"]],8:[["Water","$71","bg-amber-100 text-amber-700"]],10:[["Internet","$90","bg-amber-100 text-amber-700"]],14:[["Car payment","$520","bg-amber-100 text-amber-700"]],18:[["Insurance","$240","bg-amber-100 text-amber-700"]],22:[["Savings","$600","bg-violet-100 text-violet-700"]]};
  return <div className={cn("mt-5 grid grid-cols-7 overflow-hidden rounded-xl border border-slate-200",full&&"min-h-[520px]")} >{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><div key={d} className="border-b border-slate-200 bg-slate-50 p-2 text-center text-[10px] font-bold text-slate-500">{d}</div>)}{Array.from({length:35},(_,i)=>{const day=i-5;return <div key={i} className={cn("min-h-20 border-b border-r border-slate-100 p-1.5",full&&"min-h-28",day<1&&"bg-slate-50/60")}><span className="text-[10px] text-slate-500">{day>0&&day<=31?day:""}</span>{events[day]?.map(([name,amount,color])=><div key={name} className={cn("mt-1 truncate rounded px-1.5 py-1 text-[9px] font-bold",color)}>{name} {full&&amount}</div>)}</div>})}</div>;
}

export function ReportsFeaturePage() {
  const data=[{m:"Mar",income:7740,expenses:5720,saved:700},{m:"Apr",income:8050,expenses:6180,saved:650},{m:"May",income:7920,expenses:5840,saved:800},{m:"Jun",income:8350,expenses:6520,saved:580},{m:"Jul",income:8180,expenses:5990,saved:900},{m:"Aug",income:8520,expenses:5322,saved:1000}];
  function exportCsv(){const csv="Month,Income,Expenses,Saved\n"+data.map(d=>`${d.m},${d.income},${d.expenses},${d.saved}`).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="household-report.csv";a.click();toast.success("CSV report downloaded");}
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Reports</h1><p className="mt-1 text-sm text-slate-500">Understand your progress and spot the patterns that matter.</p></div><div className="flex gap-2"><button onClick={()=>window.print()} className="flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold"><FileText className="size-4"/>Print / PDF</button><button onClick={exportCsv} className="flex h-10 items-center gap-2 rounded-xl bg-navy px-4 text-xs font-bold text-white"><Download className="size-4"/>Export CSV</button></div></div><Summary items={[["Total income","$8,520"],["Total spending","$5,322"],["Money remaining","$3,198","text-emerald-600"],["Savings rate","11.7%","text-emerald-600"]]}/><div className="mt-4 grid gap-4 xl:grid-cols-[1.3fr_.7fr]"><Card><h2 className="font-bold">Income vs. expenses</h2><p className="mt-1 text-xs text-slate-500">Six-month household trend</p><div className="mt-4 h-72"><ResponsiveContainer><BarChart data={data}><CartesianGrid stroke="#eef0f2" vertical={false}/><XAxis dataKey="m" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v=>`$${v/1000}k`}/><Tooltip formatter={v=>formatCurrency(Number(v))}/><Bar dataKey="income" fill="#00a866" radius={[5,5,0,0]}/><Bar dataKey="expenses" fill="#111827" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card><h2 className="font-bold">August insights</h2><div className="mt-5 space-y-4">{[["Your spending decreased 11%","Compared with July","text-emerald-600 bg-emerald-50"],["Groceries is your largest flexible category","$620 this month","text-amber-700 bg-amber-50"],["You kept $3,198 after expenses","37.5% of household income","text-blue-700 bg-blue-50"]].map(([a,b,c])=><div key={a} className={cn("rounded-xl p-4",c)}><p className="text-xs font-bold">{a}</p><p className="mt-1 text-[10px] opacity-70">{b}</p></div>)}</div></Card></div></div>;
}

export function SettingsFeaturePage() {
  const sections=[["Household profile","Name, partners, currency, and budget month",Home],["Partner invitation","Invite Maya or manage household access",Mail],["Categories","Customize bill and spending categories",Settings2],["Notifications","Bill reminders, email, and activity alerts",Bell],["Approval rules","Review purchases over your chosen amount",Check],["Data and privacy","Export or permanently delete household data",Shield]];
  return <div><Heading title="Household settings" description="Make Couples Budget work the way your household does." action="Invite partner"/><div className="mt-6 grid gap-4 xl:grid-cols-[.7fr_1.3fr]"><Card><h2 className="font-bold">Settings</h2><div className="mt-4 space-y-1">{sections.map(([title,desc,Icon],i)=><button key={String(title)} className={cn("flex w-full items-center gap-3 rounded-xl p-3 text-left",i===0&&"bg-emerald-50")}><span className={cn("grid size-9 place-items-center rounded-lg bg-slate-100 text-slate-500",i===0&&"bg-white text-emerald-600")}><Icon className="size-4"/></span><div><p className="text-xs font-bold">{String(title)}</p><p className="mt-0.5 text-[10px] text-slate-500">{String(desc)}</p></div></button>)}</div></Card><Card><h2 className="font-bold">Household profile</h2><p className="mt-1 text-xs text-slate-500">Shared details visible to both partners.</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><SettingField label="Household name" value="Abel & Maya Household"/><SettingField label="Preferred currency" value="USD — US Dollar"/><SettingField label="Partner 1" value="Abel Tesfaye"/><SettingField label="Partner 2" value="Maya Tesfaye"/><SettingField label="Budget month starts" value="1st of each month"/><SettingField label="Monthly savings target" value="$1,000"/></div><div className="mt-6"><label className="text-xs font-bold">Large expense approval threshold<div className="mt-2 flex h-11 items-center rounded-xl border border-slate-200 px-3"><span className="text-slate-400">$</span><input defaultValue="500" className="w-full px-2 text-sm outline-none"/></div></label><p className="mt-2 text-[10px] text-slate-400">Your partner will be asked to review expenses above this amount.</p></div><button onClick={()=>toast.success("Household settings saved")} className="mt-7 rounded-xl bg-brand px-5 py-3 text-xs font-bold text-white">Save changes</button><button onClick={()=>toast.error("Demo data removal requires confirmation")} className="ml-2 mt-7 rounded-xl border border-red-200 px-5 py-3 text-xs font-bold text-red-600"><Trash2 className="mr-2 inline size-3"/>Remove demo data</button></Card></div></div>;
}
function SettingField({label,value}:{label:string;value:string}){return <label className="text-xs font-bold">{label}<input defaultValue={value} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 font-normal outline-none focus:border-emerald-400"/></label>}
